### ISSUE TITLE
Using dp in SimCLR with --online_ft

### ISSUE THREAD

**Issue by ananyahjha93** [PyTorchLightning/pytorch-lightning-bolts#125]
## 🐛 Bug

SimCLR module crashes when running with dp backend and --online_ft flag with an assertion error during validation sanity check.

![Screen Shot 2020-07-22 at 3 41 04 AM](https://user-images.githubusercontent.com/7491256/88148873-3ff55b80-cbcd-11ea-8764-4d45e7e990f2.png)

### To Reproduce

1. Run  python simclr_module.py --gpus 2 --distributed_backend dp --online_ft

### Expected behavior

SimCLR should run on dp distributed_backend.

**Comment by williamFalcon** [comment]
fixed
