### ISSUE TITLE
Add image vision datasets as Base lightningModules

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning-bolts#14]
Add the torchvision datasets including the standard transforms and splits as modules

```python

class MNISTModule(pl.LightningModule):

    def prepare_data(self):
        self.mnist_train = MNIST(os.getcwd(), train=True, download=True, transform=transforms.ToTensor())
        self.mnist_test = MNIST(os.getcwd(), train=False, download=True, transform=transforms.ToTensor())

    def train_dataloader(self):
        loader = DataLoader(self.mnist_train, batch_size=self.hparams.batch_size, num_workers=self.hparams.num_workers)
        return loader

    def val_dataloader(self):
        loader = DataLoader(self.mnist_test, batch_size=self.hparams.batch_size, num_workers=self.hparams.num_workers)
        return loader

    def test_dataloader(self):
        loader = DataLoader(self.mnist_test, batch_size=self.hparams.batch_size, num_workers=self.hparams.num_workers)
        return loader

```
```python
from pytorch_lightning.bolts.dataset_modules import MNISTModule

class MyModel(MNISTModule, pl.LightningModule):

    # all the dataloaders have been implemented with MNIST

```

**Comment by williamFalcon** [comment]
@PyTorchLightning/core-contributors is this a good pattern?

**Comment by williamFalcon** [comment]
i think it's any known research dataset (Norb, stl10, etc...), even esoteric ones. But not personal ones?

So, yes, curated by the community I guess

**Comment by justusschock** [comment]
Even ones the user has to download by himself? You can't download all of them in a scripted way...

**Comment by edgarriba** [comment]
I agree with @williamFalcon to only include curated datasets and potentially all from torchvision since it has a quite robust API. In case of missing ones, I think it's best to invest in contributing to torchvision instead of start creating custom stuff. For downloading, I would give the control to the user. Not all of the datasets in torchvision have really this option since in some of them you have to download the data in an offline process.

**Comment by Borda** [comment]
the only limitations with `torchvision` is that they require latest `torch`

**Comment by justusschock** [comment]
Yes, but for most datasets also previous torchvision holds them. So you could introduce a min torchvision version to each of them and check these during init :)

**Comment by williamFalcon** [comment]
these are added!

**Comment by williamFalcon** [comment]
we need to evaluate direct support with PL after we test this for a bit
