### ISSUE TITLE
For Pytorch 1.6 the LARS implementation seems incorrect?

### ISSUE THREAD

**Issue by bhokaal** [PyTorchLightning/pytorch-lightning-bolts#154]
I tried using the LARS optimizer for SimCLR but the training was not giving desirable result. Looked into the code and observed in the line below-
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/dc3ac7c6221773749ab8cec538ece8e2b4381789/pl_bolts/optimizers/layer_adaptive_scaling.py#L114

we have add() vs. add_()?

Thanks

**Comment by ananyahjha93** [comment]
@bhokaal we are adding a new version for this pretty soon. We will be removing this implementation of LARS.

**Comment by ananyahjha93** [comment]
@bhokaal for now we are experimenting between:
1. https://github.com/kakaobrain/torchlars
2. LARC found in apex

you can start using one of those two in you experiments. I am updating the simclr branch as the we get results from different runs

**Comment by DonkeyShot21** [comment]
Any news on this?
I see a new [implementation](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/optimizers/lars_scheduling.py). Has it been tested?

**Comment by Borda** [comment]
@ananyahjha93 ^^ ?

**Comment by ananyahjha93** [comment]
yes the current LARS implementation works fine in the tests we have run.
