### ISSUE TITLE
Base Networks Module

### ISSUE THREAD

**Issue by djbyrne** [PyTorchLightning/pytorch-lightning-bolts#155]
## 🚀 Feature
Have a series of base networks that are configurable in order to act as a base or backbone for other bolts models

### Motivation

Many models use a common CNN/RNN/MLP backbone which is then added to or built on top of. I think it would be really useful to have a common module containing base implementations of common models that are configurable and usable across a variety of models. This will make bolts implementations more modular and make it easier to extend models for our users. 

### Pitch

Have a networks module in bolts. This would allow users to pass in a basic network structure for base networks like CNN/MLP.
The network object would take in a dict or config file with network info (i.e layers, nodes, input, ouput) and the appropriate network would be instantiated and returned  

### Alternatives

Each specific model creates model code as needed. This may end up having  several redundant networks in the repo.

**Comment by ananyahjha93** [comment]
@djbyrne this is a good idea, we are already using a common resnet for self-supervised learning tasks and then we have linear evaluators and projection heads shared over there.
