### ISSUE TITLE
[Representation Learning] MoCo licensing issues

### ISSUE THREAD

**Issue by OlivierDehaene** [PyTorchLightning/pytorch-lightning-bolts#178]
## 📚 Documentation

MoCo is licensed under "Attribution-NonCommercial 4.0 International". There should be a mention somewhere that the pytorch-lightning-bolts modified versions is also non-commercial.

**Comment by williamFalcon** [comment]
Thanks for letting us know! We'll make that fix asap.

@ananyahjha93 FYI
