### ISSUE TITLE
Add logger for Azure Machine Learning

### ISSUE THREAD

**Issue by dkmiller** [PyTorchLightning/pytorch-lightning-bolts#180]
(Migrated over from [Add logger for Azure Machine Learning #3128](https://github.com/PyTorchLightning/pytorch-lightning/issues/3128).)

## 🚀 Feature

We already have PyTorch Lightning loggers for Comet, MLFlow, and Neptune. It would be great if we also had one for [Azure Machine Learning](https://docs.microsoft.com/en-us/azure/machine-learning/) (AML).

### Motivation

A data scientist hoping to use PyTorch Lightning in AML currently has to build their own "logger adapter" to get logs from their training runs to show up in the AML "metrics" UI like this:

![image](https://user-images.githubusercontent.com/5003801/91076946-1927ac00-e5f5-11ea-9093-bb90f9f69969.png)

It would be great if a user could just "drop in" an AML logger and get those kinds of metrics for free.

### Pitch

The AML logging API is very similar to PyTorch Lightning's, with the small caveat that AML uses the terms "experiment" and "run" slightly differently than PyTorch Lightning does. I've even coded up a preliminary implementation with unit tests here: [dkmiller/pytorch-lightning-bolts](https://github.com/PyTorchLightning/pytorch-lightning-bolts/compare/master...dkmiller:master).

### Alternatives

The only alternative I can think of is for individual users to build their own AML :: PyTorch Lightning loggers.

### Additional context

Full disclosure: I'm a data scientist in the Azure Machine Learning team.

**Comment by nateraw** [comment]
Here's a really sketchy snippet from something I wrote on an older version of lightning...super hacky, but should get ya 80% of the way there. I moved away from AzureML as I found it too time consuming to develop on + their built in visualizations aren't so easy on the eyes.

Please submit a PR if ya clean er up and get it tested! 

---

```python
import pytorch_lightning as pl
from azureml.core.run import Run

from pytorch_lightning import Trainer
from pytorch_lightning.loggers import LightningLoggerBase
from pytorch_lightning.utilities import rank_zero_only

# get the Azure ML run object
child_run = Run.get_context()
# If I remember correctly, this is some secret sauce...has to do w/ how logs are surfaced in AzureML
run = child_run.parent


class AzureMLLogger(LightningLoggerBase):
    def __init__(self):
        super().__init__()

    @rank_zero_only
    def log_hyperparams(self, params):
        pass

    @rank_zero_only
    def log_metrics(self, metrics, step):
        for k, v in {**{"step": step}, **metrics}.items():
            run.log(k, v)

    @property
    def experiment(self):
        return ""

    @property
    def name(self):
        return ""

    @property
    def version(self):
        return ""
```

---

From there you can add it to the trainer. However, ya gotta point to the reserved `'./outputs'` directory so azure doesn't throw them away. I did this by specifying it as the 'default_root_dir' arg.

```python
trainer = pl.Trainer(logger=AzureMLLogger(), default_root_dir='./outputs' )
```

**Comment by nateraw** [comment]
Oops, of course now I see you provided a first go at this 😅 . Feel free to submit PR and tag me!

**Comment by dkmiller** [comment]
Looks like the better way to handle this is via MLFLow support.
