### ISSUE TITLE
Bootstrap instead of Bring

### ISSUE THREAD

**Issue by koszpe** [PyTorchLightning/pytorch-lightning-bolts#189]
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/5326c69065ee0c73aabc9d3f624f01e8fedc7307/pl_bolts/models/self_supervised/byol/byol_module.py#L26

Bring -> Bootstrap
and the link is broken, it contains an additional point as the last character

**Comment by Borda** [comment]
@koszpe good catch, mind sending PR with a fix?
ref: https://arxiv.org/abs/2006.07733

**Comment by koszpe** [comment]
It's already done with this PR:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/220
