### ISSUE TITLE
Create a Contributing.md file

### ISSUE THREAD

**Issue by oke-aditya** [PyTorchLightning/pytorch-lightning-bolts#212]
## 🚀 Feature

Just a simple `.md` or `.rst` file which will help people to get going while contributing.

There are a lot of stuff which people keep stumbling, e.g. linting, docs, tests, CI, etc. which are not actually known at the time of PR for newcomers.

Also, we should have clarification about models since this repo is for models mainly

As discussed, what models should go in pl-bolts is also a major question that we can answer in this file.

1. Many papers claim SOTA and to really reproduce results is terribly hard.
2. Less SOTA but more used features are too necessary, e.g. mobilenet backbones in detection models.
3. API should remain consistent, we cannot keep say Pascal VOC format support for FRCNN and then COCO for Detr, it will create inconsistency for the user.
4. Open source licensing, not all are highly permissive like MIT, some are under Apache or GPL.
5. Support for old models, 
E.g. we know that Deep Lab does better than U-Net or LinkNet, do we still add them as they were popular and used before?
E.g. Efficient-Det does better than FRCNN but it might be wise to support both as both have some caveats at few places.
E.g. If we add Retina Net (probably with torchvision very soon), It is a very good single-stage detector, we might not need to use SSD detectors, they aren't so good.

New SOTA models keep popping in every field, (every year rather) how to keep supporting and deprecating.

6. Production support. Pretrained weights are sometimes hard to train and find. Models and implementations are SOTA but weights aren't, what do we do then ?

Feel free to add points further too.

cc @Borda @williamFalcon @ananyahjha93 @nateraw

**Comment by Borda** [comment]
> * Many papers claim SOTA and to really reproduce results is terribly hard.

for these cases we would like to authors contribute with their work, they may implemented as the stand also repo and optionally we could pull it into bolts

> * Less SOTA but more used features are too necessary, e.g. mobilenet backbones in detection models.

well these milestones are very needed (mostly they were sota in their time), on the other hand, they are usually already implemented in other libraries some we can just import them

> * API should remain consistent, we cannot keep say Pascal VOC format support for FRCNN and then COCO for Detr, it will create inconsistency for the user.

We should stick with DataModule format, or make a common data converters? @nateraw 

> * Open source licensing, not all are highly permissive like MIT, some are under Apache or GPL.

We would like to prefer Apache, but it is still open question

> New SOTA models keep popping in every field, (every year rather) how to keep supporting and deprecating.

I do not think we should remove any if better methods pop up, it is up to the user what method he wants to use

**Comment by oke-aditya** [comment]
Results are hard to reproduce sometimes because some are in other frameworks such as tensorflow. 

These need to be converted to torch and sometimes hyper parameters keep causing issues. 

E.g. efficient net is very hard to replicate results in torch and it is difficult to port tf weights easily. But again this model is very popular. 

I'm unsure how we go about these. For PyTorch based models we can probably port them quite easily. 

Rest all looks clear. We should support as many as we can while keeping consistent API no surprises to user.

**Comment by oke-aditya** [comment]
As discussed over slack 

1. Which are standard baselines
2. Results are reproduced properly either by us or by authors.
3. Top models which are not SOTA but highly cited for production usage / for other uses. (E.g. Moible BERT, MobileNets, FBNets).

And of course not reinvent the wheel, natively support torchvision, torchtext, torchaudio models

**Comment by nateraw** [comment]
@oke-aditya you want to do it? can assign you. Should be nearly a copy paste from lightning's contributing.md file (unless you want to rewrite it better here 😉 ).

**Comment by oke-aditya** [comment]
Yep! I can do this, I will need a review from all though at places 👍

**Comment by oke-aditya** [comment]
@nateraw I cannot find contributing.md in the [lightning](https://github.com/PyTorchLightning/pytorch-lightning) repo!
Maybe I'm missing it somewhere.

**Comment by Borda** [comment]
> @nateraw I cannot find contributing.md in the [lightning](https://github.com/PyTorchLightning/pytorch-lightning) repo!
> Maybe I'm missing it somewhere.

https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/CONTRIBUTING.md
