### ISSUE TITLE
Use SimCLR with custom input resolution

### ISSUE THREAD

**Issue by alex5995** [PyTorchLightning/pytorch-lightning-bolts#227]
I tried using the SimCLR implementation with a custom dataset, but I had some troubles while changing the input resolution. In the examples, 32x32 images are used, but I wanted to use, e.g., 128x128 images.

To do this, I overwrote the SimCLR class as follows:

```
from pl_bolts.models.self_supervised import SimCLR
from torchvision.models import resnet50
from torch.nn import Sequential

class mySimCLR(SimCLR):
    def init_encoder(self):
        encoder = resnet50()
        encoder = Sequential(*list(encoder.children())[:-1])
        return encoder
```

Then I had problems with the `GaussianBlur` class from `pl_bolts.models.self_supervised.simclr.simclr_transforms`. Indeed, if `kernel_size` is odd, the `cv2` package returns an error while calling the `cv2.GaussianBlur` function. As the `kernel_size` depends on the resolution, with some resolutions the `GaussianBlur` transformation returns an error. I solved this problem changing the `__init__` function of the `GaussianBlur` class as follows:

```
def __init__(self, kernel_size, min=0.1, max=2.0):
    self.min = min
    self.max = max
    if kernel_size % 2:
        self.kernel_size = kernel_size
    else:
        self.kernel_size = kernel_size + 1
```

I don't know if it could be a good solution or not, but it made the job for me.
Maybe the `GaussianBlur` class could be edited as suggested for dealing with different input resolutions or maybe this example could be useful for someone.

Anyway, I would like to know your opinion about this problem and the solution I found.

**Comment by ananyahjha93** [comment]
We'll update the class to take care of odd kernel sizes.

**Comment by FrankXinqi** [comment]
I cannot make GaussianBlur work on my datast either. Looking forward for an update, or point out some ideas to change.

Currently, I comment the GaussianBlur transformation.

**Comment by alex5995** [comment]
Have you tried with my solution? You should add 1 to the kernel size if it is even, as shown in the second snippet of code.

PS: I figured out that I wrote "odd" in the issue, but the cv2.GaussianBlur function does not work with even kernel sizes. Anyway the snippet of code is correct. I only made a mistake while writing the issue.
