### ISSUE TITLE
Citing this repository

### ISSUE THREAD

**Issue by yaminibansal** [PyTorchLightning/pytorch-lightning-bolts#244]
Is there a preferred way to cite this repository for research publications? 

Thanks for all the hard work!

**Comment by williamFalcon** [comment]
yup! at the bottom of the readme is the bibtex

**Comment by ethanjperez** [comment]
@williamFalcon is the citation malformed? It appears as "William Falcon and .al" - maybe you meant "William Falcon et al."?

**Comment by equaeghe** [comment]
I don't find the bib file anymore. In any case, it should use @misc or @online type, not @article. Furthermore, the BibTeX way to say ‘William Falcon et al.’ is to say ‘William Falcon and others’.

**Comment by Borda** [comment]
@equaeghe added reference with Zenodo - https://zenodo.org/record/7447212#.Y5x0PdLMKV4
