### ISSUE TITLE
pin_memory should be true only if gpus are specified

### ISSUE THREAD

**Issue by igormq** [PyTorchLightning/pytorch-lightning-bolts#245]
Hey folks,

First of all, thank you for this amazing package. It has saved many hours of coding :) 

I was using for the first time the pl data modules when I hit the following line
[cifar10_datamodule.py#L132](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/c2cdad7c12e4d33ed39db808879706c608c1c7/pl_bolts/datamodules/cifar10_datamodule.py#L132). The problem is: when I am training/evaluating/testing on CPU, the data module try to pin the data and try to reserve a batch size memory amount in gpu. Nothing goes wrong if I have GPU with enough memory ran, but, when I try to run in CPU mode with all my GPUs in use I get the following error:

```
RuntimeError: Caught RuntimeError in pin memory thread for device 0.
Original Traceback (most recent call last):
  File "/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 31, in _pin_memory_loop
    data = pin_memory(data)
  File "/lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in pin_memory
    return [pin_memory(sample) for sample in data]
  File "lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 55, in <listcomp>
    return [pin_memory(sample) for sample in data]
  File "lib/python3.7/site-packages/torch/utils/data/_utils/pin_memory.py", line 47, in pin_memory
    return data.pin_memory()
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1595629427478/work/aten/src/THC/THCCachingHostAllocator.cpp:278
```

The fix is simple and we can borrow the code from the pl core implementation as in [pytorch_lightning/accelerators/accelerator_connector.py#L90](https://github.com/PyTorchLightning/pytorch-lightning/blob/0045119b3fd4532bf8edf17dcbaeba9bc66ba25b/pytorch_lightning/accelerators/accelerator_connector.py#L90)

Bests.

**Comment by nateraw** [comment]
@igormq mind sending a PR? if not I can address this.

**Comment by nateraw** [comment]
I think the main thing here is to just include the `pin_memory` flag in the datamodules. I think by default it makes sense to set it to True either way? please correct me if I'm wrong 😄

**Comment by briankosw** [comment]
@nateraw I think even beyond the `pin_memory` flag, some other flags should also be included such as the `shuffle` and `drop_last` flag. What do you think? I can work on a pull request for updating the flags in the datamodules.

**Comment by nateraw** [comment]
@briankosw sure! for the `shuffle` and `drop_last` flags, lets just make sure we use sensible defaults. 😄  Thanks!!
