### ISSUE TITLE
Add custom encoder support for SimCLR

### ISSUE THREAD

**Issue by alyashgo** [PyTorchLightning/pytorch-lightning-bolts#294]
## 🚀 Feature
Right now the SimCLR module uses the vanilla resnet50 as encoder with the first conv block replaced assuming image size to be 32. See below
```python
def init_encoder(self):
        encoder = resnet50_bn(return_all_feature_maps=False)

        #when using cifar10, replace the first conv so image doesn't shrink away
        encoder.conv1 = nn.Conv2d(
            3, 64,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=False
        )
        return encoder
```
### Motivation
Adding encoder as an argument in the init method would allow seamless ablation studies by trying out different architectures. Making the replacement of first conv block conditional on the image size will prevent unnecessary computational overhead which not desirable for large image sizes(eg. 256). This would improve training.

**Comment by ananyahjha93** [comment]
@alyashgo we've added a generic resnet backbone and you can sub-class the simclr module or replace the encoder in your code now. SimCLR has been updated.

**Comment by alyashgo** [comment]
Thanks a lot @ananyahjha93 !
