### ISSUE TITLE
docs: Add Bolts logo

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#298]
## 🚀 Feature
Not a strong opinion, but I would like to suggest a change to the logo image located at the top left in https://pytorch-lightning-bolts.readthedocs.io/en/. Currently, both `pytorch-lightning` and `pytorch-lightning-bolts` docs use the same logo image, and I personally think that makes it somewhat confusing. It would be much easier to distinguish them if the `pytorch-lightning-bolts` logo is different from `pytorch-lightning` logo.

**Comment by FrankXinqi** [comment]
A good point. I was confused about the jump between different docs content, but did not figure out the reason.
Now, I see one doc for pl, and one for pl-blots.
