### ISSUE TITLE
docs: Fix URI links to classes defined in `pytorch_lightning`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#306]
## 📚 Documentation
In docs, there are URIs referring to base classes for each class defined in bolts. However, links to `pytorch_lightning` are not properly rendered while links to `torch` are perfectly rendered.

### Example
https://pytorch-lightning-bolts.readthedocs.io/en/latest/datasets.html#dummydataset
![20201025-011752](https://user-images.githubusercontent.com/20610905/97086703-f9961980-165f-11eb-96ba-32aadbffe9c7.png)
https://pytorch-lightning-bolts.readthedocs.io/en/latest/vision_datamodules.html#binarymnist
![20201025-011742](https://user-images.githubusercontent.com/20610905/97086705-fa2eb000-165f-11eb-9659-bc4896bd2cef.png)

### Additional context
I tried to fix this issue by adding a line:
`    'pytorch_lightning': ('https://pytorch-lightning.readthedocs.io/en/stable/', None),`
to `intersphinx_mapping` at
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/f0939f62a5559a9a68cbb60ab8cbddac8c42cb05/docs/source/conf.py#L255
but it didn't make any change in docs.

**Comment by ydcjeff** [comment]
@akihironitta Thank you for finding out. Actually It worked! You can see in the bolts callbacks docs.
But it won't for `LightningDataModule` as there is no `LightningDataModule` API docs in Lightning.
But there is a PR doing that https://github.com/PyTorchLightning/pytorch-lightning/pull/3950

So, could you try to send a PR for that?

**Comment by akihironitta** [comment]
@ydcjeff Thank you for the response.
> But it won't for LightningDataModule as there is no LightningDataModule API docs in Lightning.
That's why I thought it didn't work! I'll submit a PR in no time :]
