### ISSUE TITLE
visdom logger

### ISSUE THREAD

**Issue by sumanthratna** [PyTorchLightning/pytorch-lightning-bolts#310]
## 🚀 Feature
Comet, MLFlow, Neptune, TensorBoard, test-tube, WandB, and CSV are the supported loggers as of 08/31/2020. It would be great if Visdom was supported too.  

### Motivation
just a matter of preference. one nice feature of visdom is that it allows users to organize views. Visdom also caches state. 

### Pitch

an API that looks like the other loggers, but uses visdom instead

### Alternatives

The most reasonable way to implement this would be to add a Visdom logger here: 
https://github.com/PyTorchLightning/pytorch-lightning/tree/master/pytorch_lightning/loggers

### Additional context

n/a

**Comment by awaelchli** [comment]
Is it still maintained?

**Comment by sumanthratna** [comment]
Hmmm...looks like they're looking for someone to take on the project as a maintainer: https://github.com/facebookresearch/visdom/issues/753. I think PTL Bolts should probably wait for a month or two and see if anyone volunteers to maintain visdom

**Comment by ananyahjha93** [comment]
Without any active support for visdom, we don't have any plans of supporting it for now. If it does become active again, we can think about it. Closing it for now, let's open this if visdom has some movement.

**Comment by vedal** [comment]
visdom has now been moved to open-source and seems to be in active development

https://github.com/fossasia/visdom
https://blog.fossasia.org/welcome-the-visdom-project-at-fossasia-now-fully-open-source/
