### ISSUE TITLE
Upgrade bolts to Lightning 1.0.3

### ISSUE THREAD

**Issue by edenlightning** [PyTorchLightning/pytorch-lightning-bolts#313]

**Comment by Borda** [comment]
We are already testing against the latest PL version so what is the point here?
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.github/workflows/ci_test-full.yml#L21

**Comment by ananyahjha93** [comment]
Closing this, I think bolts is already above 1.0.3.

**Comment by Borda** [comment]
it is not, but it is not needed..
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/77ff983085cc4889b9cb5a439ec3eb2b2536599c/requirements.txt#L2
