### ISSUE TITLE
Several datamodules ignoring batch_size

### ISSUE THREAD

**Issue by hecoding** [PyTorchLightning/pytorch-lightning-bolts#334]
## 🐛 Bug

Realized `MNISTDataModule` was ignoring `batch_size` parameter. I found a closed issue (#171) referring to that without a fix.

While fixing it myself (PR #331), I found more datamodules had this problem too - `MNISTDataModule`, `BinaryMNISTDataModule`, `FashionMNISTDataModule`, `SklearnDataModule`, `SSLImagenetDataModule`.

I could take care of that. My question is, is this signature from MNIST in use anymore?:
```python
def train_dataloader(self, batch_size=64, transforms=None):
```
That is basically where the bug comes from. Other datamodules working fine, like `CIFAR10DataModule`, are simply:
```python
def train_dataloader(self):
```

Same thing goes for `val_dataloader` and `test_dataloader`.

### To Reproduce

1. Set up `MNISTDataModule` to use a batch size anything else than 32.
2. Run an experiment
3. Check the batch sizes are 32 regardless

#### Code sample

```python
from pytorch_lightning.core.lightning import LightningModule
from pytorch_lightning import Trainer
from pl_bolts.datamodules.mnist_datamodule import MNISTDataModule

batch_size = 64


class SampleModel(LightningModule):
    def configure_optimizers(self):
        pass

    def training_step(self, batch, batch_idx):
        x, y = batch
        assert x.shape[0] == batch_size
        print('fine')


model = SampleModel()
dm = MNISTDataModule(data_dir='~/Datasets/', batch_size=batch_size)

trainer = Trainer()
trainer.fit(model, dm)
```

### Expected behavior
Batch sizes of 64.
Printing `fine` instead of assert error.

### Environment

 - PyTorch Version (e.g., 1.0): 1.7
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information: pytorch-lightning-bolts 0.2.5

**Comment by ananyahjha93** [comment]
@hecoding send in the PR. 

the signature is ``def train_dataloader(self):``. The datamodule class init should take the batch size params and not the ``train_dataloader``.

**Comment by hecoding** [comment]
Cool, I fixed the signatures too. Please @ananyahjha93 have a look at the PR here #331 
Should I assign somebody for review myself? I'm a bit lost on that.

**Comment by hecoding** [comment]
I can fix the rest of the data modules listed too. Let me know.
