### ISSUE TITLE
Refactor `pl_bolts/datamodules`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#337]
## 🚀 Refactoring
Currently, there are `try: ... except: ...` in `pl_bolts/datamodules/__init__.py` which were added in #303, and it is not clean in my humble opinion.

In order to make `__init__.py` clean and keep the behaviour, the following steps are needed:
1. Remove `try: ... except: ...` in `__init__.py`.
2. Rewrite optional imports (`torchvision`, `sklearn`, `gym`...) in `pl_bolts/datamodules/*.py` with `importlib.util.find_spec("some_package") is not None` in order not to raise `ModuleNotFoundError` with `from pl_bolts.datamodules import ...` The way of importing optional packages was suggested by @awaelchli in https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/290#issuecomment-714247909

### Additional context
These `try: ... except: ...` were added in #303 to fix the import problem in #291 where `from pl_bolts.datamodules import MNISTDataModule` raises `ModuleNotFoundError` even if the requirements for `MNISTDataModule` were met.

I would be happy to submit a PR if it sounds reasonable to you!

**Comment by ananyahjha93** [comment]
@akihironitta I think this would be a good enhancement. Go for it, send in the PR.

**Comment by Borda** [comment]
cc: @awaelchli
