### ISSUE TITLE
SimCLR doesn't seem to utilize GPU for forward/backward passes

### ISSUE THREAD

**Issue by kylepula** [PyTorchLightning/pytorch-lightning-bolts#35]
## 🐛 Bug

When running the pl_bolts simclr implementation on cifar10 and my own dataset, I see very low GPU utilization and only at the very beginning of the validation sanity check. After that, `nvidia-smi` reports that the job holds on to a bit of GPU memory but never shows GPU utilization above 0%.

There was also a missing import of `ArgumentParser` here https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/977f2ed92694d9de1d05b4c53efbf149192505b4/pl_bolts/models/self_supervised/simclr/simclr_module.py#L247

### To Reproduce

Run the following:
```bash
python -m pl_bolts.models.self_supervised.simclr.simclr_module --dataset cifar10 --ma
x_epochs=1 --profiler=True
```
Watch GPU utilization via `nvidia-smi`. I see a small spike at the start of validation sanity check and then 0%.

#### Code sample

See above

### Expected behavior

Higher GPU Utilization

### Environment

pytorch-lightning                  0.7.6
pytorch-lightning-bolts            0.1.0.dev8
torch                              1.5.0
torchvision                        0.6.0a0+82fd1c8
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): AWS Deep Learning AMI w/ pytorch_latest_py36 conda pre-built environment
 - Build command you used (if compiling from source): Pre-built in AMI
 - Python version: 3.6.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: Tesla K80, driver 440.33.01
 - Any other relevant information:

**Comment by williamFalcon** [comment]
simclr is still in development! it should be using GPUs bc of lightning, but it might still need some work.

Welcome all PRs!

**Comment by ananyahjha93** [comment]
simclr_module.py requires the user to provide the --gpus flag with the command "python simclr_module.py --gpus 1" for now. We are looking into the issue to remove the confusion regarding the gpus flag.

**Comment by ananyahjha93** [comment]
Fixed in PR: https://github.com/PyTorchLightning/pytorch-lightning/pull/2674 of Lightning
