### ISSUE TITLE
update chnagelog

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/pytorch-lightning-bolts#351]
## 📚 Documentation

Let's keep changelog at least in the basic outlines - list added features like RL package or breaking changes. We do not need to be as detail as PT but keeping some overview would be nice, then we can also include it in [docs as PL](https://pytorch-lightning.readthedocs.io/en/stable/CHANGELOG.html)

**Comment by akihironitta** [comment]
@Borda Let me work on this issue :]
