### ISSUE TITLE
Trying to simply download mnist and train. getting RuntimeError: Dataset not found. You can use download=True to download it

### ISSUE THREAD

**Issue by simeneide** [PyTorchLightning/pytorch-lightning-bolts#353]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
Tried to get a simple mnist example working from bolts and lightning, but ended up in this error. It seems like the data are downloaded correctly the first time but that the files are in wrong format or similar. All fixes Ive seen seem very complex for such a "simple" task to be running. (e.g. a separate script that prepares the data).

Replicated in google colab (see link below).

#### Code

`
!pip install pytorch-lightning pytorch-lightning-bolts -q
from pl_bolts.datamodules import BinaryMNISTDataModule
import torch
from torch.nn import functional as F
from torch import nn
from pytorch_lightning.core.lightning import LightningModule
from pytorch_lightning import Trainer, seed_everything

class LitMNIST(LightningModule):
    def __init__(self):
        super().__init__()
        self.layer_1 = torch.nn.Linear(28 * 28, 128)
        self.layer_2 = torch.nn.Linear(128, 256)
        self.layer_3 = torch.nn.Linear(256, 10)

    def forward(self, x):
        batch_size, channels, width, height = x.size()
        x = x.view(batch_size, -1)
        x = self.layer_1(x)
        x = F.relu(x)
        x = self.layer_2(x)
        x = F.relu(x)
        x = self.layer_3(x)
        x = F.log_softmax(x, dim=1)
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        logits = self(x)
        loss = F.nll_loss(logits, y)
        return loss
        
    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer
model = LitMNIST()
dm = BinaryMNISTDataModule('.')
Trainer().fit(model, dm)
`

#### What have you tried?
Have I misunderstood how to use bolts or is this a bit hard? The code should be pretty much copy paste from tutorials to get a fully working example as seen here:
https://pytorch-lightning-bolts.readthedocs.io/en/latest/api/pl_bolts.datamodules.html#pl_bolts.datamodules.BinaryMNISTDataModule

Relevant post: https://discuss.pytorch.org/t/cant-load-dataset-using-dataloader/34831/2
#### What's your environment?
https://colab.research.google.com/drive/1MovSwV87jxaLod3Hbs-rnmlNg0eyKBeS?usp=sharing

**Comment by annikabrundyn** [comment]
Thanks for thoroughly reporting the issue @simeneide - looking into it now! :)

**Comment by annikabrundyn** [comment]
Hi @simeneide - thanks for reporting this! We've merged a PR which fixes this :) 

https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/377

**Comment by simeneide** [comment]
Thanks! 😄
