### ISSUE TITLE
Closure Argument in Step Method - SimCLR

### ISSUE THREAD

**Issue by RudyVenguswamy** [PyTorchLightning/pytorch-lightning-bolts#354]
**Context:** We’re a team trying to build a reverse image searcher for satellite data. Currently, we’re using the UC Merced land use dataset (linked in notebook below) to train a self-supervised learner and evaluate it using the labels provided with the dataset. 

**Issue:** Using the pip installable version of pytorch-lightning-bolts, it seems SimCLR errors out with "TypeError: step() got an unexpected keyword argument 'closure'". The issue can be solved using a pip install of the bleeding edge version. However, we wanted to confirm this is the appropriate solution currently and not avoiding the fundamental issue.

**Code to Reproduce (Colab):** https://colab.research.google.com/drive/1Me0k1BBVsm1NmPRetAJT--Sd_wVg6u-k?usp=sharing

**Comment by paulxiong** [comment]
I am running into the same issue with SimCLR, exactly following the doc/example. I did run:
pip install git+https://github.com/PytorchLightning/pytorch-lightning.git@master --upgrade
but the issue still there.  
My question: "The issue can be solved using a pip install of the bleeding edge version", what version did you install to fix the issue?

**Comment by RudyVenguswamy** [comment]
I just checked it now- at least on the notebook linked above,
!pip install git+https://github.com/PytorchLightning/pytorch-lightning-bolts.git@master --upgrade
begins training if you change the batch_size to < 8 (issue with small batch size is a separate issue, CUDA OOM on colab).

**Comment by paulxiong** [comment]
Yes, it running w/o error now. I did not try the latest bolts before since that error occurred on the lighting core. Thanks.

**Comment by ananyahjha93** [comment]
@RudyVenguswamy @paulxiong the latest version of bolts and lightning should solve this issue. This was due to the LARSWrapper's step not taking any closure.

**Comment by shoaibazam** [comment]
I have installed the latest version of bolts and lightning, but I have got the same error. Kindly help me in this regard.

**Comment by shoaibazam** [comment]
I have used master repo and its working fine
