### ISSUE TITLE
Add Intersection over Union loss

### ISSUE THREAD

**Issue by briankosw** [PyTorchLightning/pytorch-lightning-bolts#370]
## 🚀 Feature

Since #251 includes GIoU loss, I think having IoU loss only makes sense.

### Pitch

I can implement this pretty quickly since I've been working on GIoU #347.

**Comment by akihironitta** [comment]
@briankosw Thank you for your suggestion! I think it'd be nice to have IoU loss as well.

As far as I understand, `GIoU loss` and `IoU loss` can share the most of the code (both use `IoU`), so it may be reasonable to extract `IoU` from `GIoU` in #347 and use it in `IoU loss` here.

**Comment by briankosw** [comment]
@akihironitta absolutely there is significantly overlap. I'll work on a PR for IoU loss!
