### ISSUE TITLE
Refactor Vision DataModules

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/pytorch-lightning-bolts#395]
## 🚀 Feature
I was going through the smaller vision data modules (CIFAR10, MNIST) and noticed that there is a lot of duplicate code in them. I would suggest creating a VisionDataModule similar to PyTorch's VisionDataset and create subclasses of it for the different data modules.

### Motivation
Makes maintaining the code easier.

If you agree, I could prepare a PR :)

**Comment by akihironitta** [comment]
@chris-clem Thank you for your suggestion! Would you mind describing more about `VisionDataModule`? In particular, any methods or attributes the class should have in your mind?

**Comment by chris-clem** [comment]
Sure, basically something like this:

```python
class VisionDataModule(pl.LightningDataModule):
    def __init__(self, hparams, dataset_cls, transform, dims):
        super().__init__()
        self.hparams = hparams
        self.dataset_cls = dataset_cls
        self.transform = transform
        self.dims = dims

    def prepare_data(self):
        self.dataset_cls(self.hparams.data_dir, train=True, download=True)
        self.dataset_cls(self.hparams.data_dir, train=False, download=True)

    def setup(self, stage=None):
        if stage == "fit" or stage is None:
            dataset_dev = self.dataset_cls(self.hparams.data_dir, train=True, transform=self.transform)
            dev_len = len(dataset_dev)
            self.dataset_train, self.dataset_val = random_split(
                dataset_dev,
                [dev_len - self.hparams.val_split, self.hparams.val_split],
                generator=torch.Generator().manual_seed(self.hparams.seed),
            )

        if stage == "test" or stage is None:
            dataset_test = self.dataset_cls(self.hparams.data_dir, train=False, transform=self.transform)
            self.dataset_test = dataset_test

    def train_dataloader(self):
        return self._dataloader(self.dataset_train, True)

    def val_dataloader(self):
        return self._dataloader(self.dataset_val, False)

    def test_dataloader(self):
        return self._dataloader(self.dataset_test, False)

    def _dataloader(self, dataset, shuffle):
        return DataLoader(
            dataset,
            batch_size=self.hparams.batch_size,
            shuffle=shuffle,
            num_workers=self.hparams.num_workers,
            drop_last=True,
            pin_memory=True,
        )

    @staticmethod
    def add_model_specific_args(parent_parser):
        parser = ArgumentParser(parents=[parent_parser], add_help=False)
        parser.add_argument("--batch_size", type=int, default=32)
        parser.add_argument("--data_dir", type=str, default="../datasets")
        parser.add_argument("--num_workers", type=int, default=12)
        parser.add_argument("--seed", type=int, default=42)
        parser.add_argument("--val_split", type=int, default=5_000)
        return parser
```

And then MNISTDataModule and CIFAR10DataModule would be something like:
```python
class MNISTDataModule(VisionDataModule):
    def __init__(self, hparams):
        transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((-1.1307,), (0.3081,))])
        dims = (1, 28, 28)
        super().__init__(hparams, MNIST, transform, dims)


class CIFAR10DataModule(VisionDataModule):
    def __init__(self, hparams):
        transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])
        dims = (3, 28, 28)
        super().__init__(hparams, CIFAR10, transform, dims)
```

**Comment by akihironitta** [comment]
@chris-clem Thank you for describing in detail! I'm actually not sure if we should add the class to Bolts...
@Borda @ananyahjha93 @annikabrundyn What do you think?

**Comment by Borda** [comment]
Yeah, I like the idea of making a general `torchvision` datamodule, just be careful that users wound misunderstood as a general-purpose data module for computer vision 🐰

**Comment by chris-clem** [comment]
@Borda, @akihironitta I added a PR :)

**Comment by ananyahjha93** [comment]
@chris-clem this looks great! reviewing the PR to see if we need refactors at some other places on the codebase.

**Comment by chris-clem** [comment]
@ananyahjha93 Yeah I think you could go deeper with the refactoring and cover all available datasets. I only took those with the same API. 

Another idea would be to provide a wrapper for all available PyTorch as almost all of them have the same API (https://pytorch.org/docs/stable/torchvision/datasets.html). The problem is the "almost" in the sentence, which makes the thing a little tricky/ ugly.

**Comment by lbugnon** [comment]
Hi, I was going to fill an issue about this but this one goes. If you ran "dataset = MNISTDataModule('.')" in a fresh install, the reported error is "RuntimeError: Dataset not found. You can use download=True to download it", which is confusing (because it is needed to run "dataset.prepare_dataset()". Thus either add this option or change the error report. Adding this to the tutorials docs may help also.
