### ISSUE TITLE
Add inhouse SOTA augmentations

### ISSUE THREAD

**Issue by kartik4949** [PyTorchLightning/pytorch-lightning-bolts#396]
## 🚀 Feature
Thinking to file a pr for transform module which consist inhouse transformations which are not present torch.transforms.
### Motivation
Gridmask, mosaic, mixup, cutmix, etc
above augmentations are missing in most of the frameworks and they are de facto for kaggle, general computer vision solutions, etc

### Reference
my library which consist all of this module -> https://github.com/kartik4949/TensorPipe

**Comment by akihironitta** [comment]
@kartik4949 Thank you for your suggestion! Your library seems very useful :]

@Borda @annikabrundyn Any thoughts?

**Comment by kartik4949** [comment]
@akihironitta thanks :)
can make explicit PRs for each augmentations.

**Comment by ananyahjha93** [comment]
@kartik4949 this seems like a good enhancement. I glanced at the code for these augmentations. 1 thing I would like to point out is, since you would be adding custom code to the library, can you add tests for these as well?

**Comment by kartik4949** [comment]
> @kartik4949 this seems like a good enhancement. I glanced at the code for these augmentations. 1 thing I would like to point out is, since you would be adding custom code to the library, can you add tests for these as well? 

Hi @ananyahjha93 thanks to review my library 
Yeah tests are lacking in my library as i was quite busy this month but will definitely add robust testing suite for them :)

**Comment by briankosw** [comment]
I think existing libraries such as [albumentations](https://github.com/albumentations-team/albumentations), [imgaug](https://github.com/aleju/imgaug/), and [kornia](https://github.com/kornia/kornia) already have a robust set of augmentation. All of them are well integrated with PyTorch as well, so I'm not sure if pl_bolts needs its own implementations.

**Comment by kartik4949** [comment]
Well they do have robust set of augmentations but they lack SOTA augmentations 
E.G 
GridMask
Mosaic
CutOut
RandomErase (imgaug have it) 
CutMix
MixUp
CopyPaste
.
.
.

**Comment by kartik4949** [comment]
closing.

**Comment by Borda** [comment]
@kartik4949 sorry for the delay, what do you think to be the advantage to have it here than in lower level lib like Kornia?
and would you be willing to implement it here? 🐰

**Comment by kartik4949** [comment]
@Borda thank you for reply :) 
But with above suggestion and also in slack suggestion found out it wont be feasible to add it here :)
