### ISSUE TITLE
How to use the pretrained SimCLR model to extract image features.

### ISSUE THREAD

**Issue by hosea7456** [PyTorchLightning/pytorch-lightning-bolts#398]
## ❓ Questions and Help
I would like to use the pretrained model of SimCLR to extract image features. I wonder if pl_bolts.models also support pretrained SimCLR model like the CPCV2 as follows?  

from pl_bolts.models.self_supervised import CPCV2
# load resnet18 pretrained using CPC on imagenet
model = CPCV2(pretrained='resnet18')
cpc_resnet18 = model.encoder

Thanks a lot!
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - OS: [e.g. iOS, Linux, Win]
 - Packaging [e.g. pip, conda]
 - Version [e.g. 0.5.2.1]

**Comment by ananyahjha93** [comment]
@hosea7456 we are in the process of updating simclr weights for cifar-10 and Imagenet. Also, to use the simclr pretrained weights, you can refer to the docs: https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html#simclr

The code below just defines the usage pattern. It needs to be updated with the latest trained weights.

```
from pl_bolts.models.self_supervised import SimCLR

weight_path = 'https://pl-bolts-weights.s3.us-east-2.amazonaws.com/simclr/simclr-cifar10-v1-exp12_87_52/epoch%3D960.ckpt'
simclr = SimCLR.load_from_checkpoint(weight_path, strict=False)

simclr.freeze()
```

**Comment by hosea7456** [comment]
@ananyahjha93 
Thanks a million.
