### ISSUE TITLE
Add DCGAN

### ISSUE THREAD

**Issue by chris-clem** [PyTorchLightning/pytorch-lightning-bolts#401]
## 🚀 Feature
How about adding a DCGAN implementation to Bolts? In a private repo, I refactored the PyTorch example implementation (https://github.com/pytorch/examples/blob/master/dcgan/main.py) to PyTorch Lightning and I am happy to create a PR with it if you want.

### Motivation

DCGAN can be used as a solid GAN baseline and therefore should be included in Bolts.

**Comment by oke-aditya** [comment]
I think the above example on pytorch is really very good implementation. It was made by authors of DCGAN papers,

**Comment by chris-clem** [comment]
I added the implementation to the PR. Will add tests tomorrow.

**Comment by chris-clem** [comment]
@akihironitta I added the tests. From my side, the PR would be ready for review :)

**Comment by oke-aditya** [comment]
Just a thought, the orignal paper uses LSUN bedroom dataset which might be nice to use!

**Comment by chris-clem** [comment]
> Just a thought, the orignal paper uses [LSUN ](https://pytorch.org/docs/stable/_modules/torchvision/datasets/lsun.html#LSUN) bedroom dataset which might be nice to use and is available in torchvision !

Good point! I will add it to the PR.
