### ISSUE TITLE
Is cifar10 num_samples correct?

### ISSUE THREAD

**Issue by koszpe** [PyTorchLightning/pytorch-lightning-bolts#408]
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/ecbb82a057c9be6caa06b0b8885743db8a1a752a/pl_bolts/datamodules/cifar10_datamodule.py#L98

The self.num_samples = 60000 - val_split may be wrong, the dataset indeed contains 60000 examples, but it includes the test set too, which size is 10000.
So I think the correct size would be 50000 - val_split

I checked it with val_split=5000, and the train_length here is 50000:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/ecbb82a057c9be6caa06b0b8885743db8a1a752a/pl_bolts/datamodules/cifar10_datamodule.py#L122

the len(dataset_train) is 45000 (not 55000) here:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/ecbb82a057c9be6caa06b0b8885743db8a1a752a/pl_bolts/datamodules/cifar10_datamodule.py#L123

It may affects the SimCLR performance, it is used here:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/ecbb82a057c9be6caa06b0b8885743db8a1a752a/pl_bolts/models/self_supervised/simclr/simclr_module.py#L400

after here:
https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/ecbb82a057c9be6caa06b0b8885743db8a1a752a/pl_bolts/models/self_supervised/simclr/simclr_module.py#L136

So it influences the lr schedule.

**Comment by Borda** [comment]
@ananyahjha93 mind have a look? :]
