### ISSUE TITLE
List all RL examples in docs

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning-bolts#41]
@djbyrne 

For each approach we need:

![image](https://user-images.githubusercontent.com/3640001/85210101-1d8ccb80-b30b-11ea-92c8-1ad28c9107aa.png)

**Comment by djbyrne** [comment]
This should be completed with https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/57
