### ISSUE TITLE
ci: Introduce static type checker

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#410]
## 🚀 Feature
As PL has `pyright` type checker in ci https://github.com/PyTorchLightning/pytorch-lightning/issues/2093, we should have one in Bolts as well.

There are a number of type checkers, and reasonable options are:
- https://github.com/python/mypy
  - Python's official project
  - easy installation with pip
  - more stars(\approx users) than pyright
- https://github.com/microsoft/pyright
  - (core members may be familiar with pyright just because PL uses it (?))

In my humble opinion, mypy would be a better choice for the reasons listed above.

### Motivation
We have type annotations in some classes and functions mainly for docs, but we're currently not sure if the added type hints are correct or not, which should be addressed.

**Comment by oke-aditya** [comment]
I guess mypy would be nice. Even torchvision uses mypy. A sample init file which might prove useful is from torchvision is [here](https://github.com/pytorch/vision/blob/master/mypy.ini).

**Comment by akihironitta** [comment]
@Borda @ananyahjha93 Can I give it a go for this? I'll first make a PR adding mypy check to GH Actions and later apply type annotations to the codebase step-by-step like applying isort in PL repo.

**Comment by Borda** [comment]
> @Borda @ananyahjha93 Can I give it a go for this? I'll first make a PR adding mypy check to GH Actions and later apply type annotations to the codebase step-by-step like applying isort in PL repo.

sure, go ahead :]
