### ISSUE TITLE
Regarding the collab notebook of simCLR

### ISSUE THREAD

**Issue by Shraban123** [PyTorchLightning/pytorch-lightning-bolts#416]
When I am trying to run the code for the simCLR notebook from your youtube channel I get the following errors:
![resnet_50_bn](https://user-images.githubusercontent.com/57726215/100546631-65cff280-3288-11eb-849e-8db05284d96f.JPG)
The above error comes when I use the resnet50_bn.
I have replaced it with resnet50.

![2](https://user-images.githubusercontent.com/57726215/100546669-8f891980-3288-11eb-82ca-3c91f7d88049.JPG)
In the above figure I had to replace:
from pl_bolts.callbacks.self_supervised import SSLOnlineEvaluator
with
from pl_bolts.callbacks.ssl_online import SSLOnlineEvaluator

The remaining code as is not visible in the above picture:
![4](https://user-images.githubusercontent.com/57726215/100546765-09b99e00-3289-11eb-9dae-54fdb8d24cbe.JPG)

Lastly, I get the following error:
![3](https://user-images.githubusercontent.com/57726215/100546691-b21b3280-3288-11eb-87c3-c0bcb457b1ea.JPG)
Is this occurring because of the changes I made?
I am running it on google collab and I have tried TPU and GPU. I get the same error.
Please help.

**Comment by justusschock** [comment]
cc @ananyahjha93

**Comment by RezwanCode** [comment]
**Hi @Shraban123 , I am facing the similar issues. Were you able to solve it?**

**Comment by ananyahjha93** [comment]
@Shraban123 @RezwanCode take a look at the updated simclr code: https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/models/self_supervised/simclr/simclr_module.py

The output of the default resnet in bolts has changed which changes the definition of projection module.

**Comment by ananyahjha93** [comment]
This should solve the bug, feel free to re-open this if the error persists!

**Comment by timothyvanco** [comment]
Hi, I still get this error. I tried to run your code from colab (link in your youtube videos) but first I got a problem with:

`from pytorch_lightning.callbacks import LearningRateLogger`

then I solved it with:

`from pytorch_lightning.callbacks.lr_monitor import LearningRateMonitor`

but now I have an error : 

```
ValueError                                Traceback (most recent call last)
<ipython-input-14-31df677ce62e> in <module>()
     34 model = SimCLR(batch_size=batch_size, num_samples=train_samples)
     35 trainer = pl.Trainer(callbacks=callbacks, progress_bar_refresh_rate=10, gpus=1)
---> 36 trainer.fit(model, dm)

18 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/utils.py in _list_with_default(out_size, defaults)
     32         return out_size
     33     if len(defaults) <= len(out_size):
---> 34         raise ValueError('Input dimension should be at least {}'.format(len(out_size) + 1))
     35     return [v if v is not None else d for v, d in zip(out_size, defaults[-len(out_size):])]

ValueError: Input dimension should be at least 3
```

please help! :)

**Comment by amirajaee** [comment]
I'm facing the same issue.

@timothyvanco Is there anywhere I can find their notebook shown on youtube?
I typed the whole thing watching their YouTubes and facing many errors.

**Comment by alaa-shubbak** [comment]
I got similar error while training the model of simclr on another backbone (HRnet-w32) 

I wounder how can i solve it while i am using the mmpretrain library 

any help please? 


also i could not find where was the update here

> @Shraban123 @RezwanCode take a look at the updated simclr code: https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/pl_bolts/models/self_supervised/simclr/simclr_module.py
> 
> The output of the default resnet in bolts has changed which changes the definition of projection module.
