### ISSUE TITLE
All data modules don't support providing batch size in the constructor.

### ISSUE THREAD

**Issue by senarvi** [PyTorchLightning/pytorch-lightning-bolts#417]
## 🐛 Bug

Half of the data loaders don't support providing batch size in the constructor, but only in the `{train,val,test}_dataloader()` methods. This means that if a data module is passed `Trainer.fit()`, the default batch size is used.

[Cifar10DataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/cifar10_datamodule.py), [CityscapesDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/cityscapes_datamodule.py), [ImagenetDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/imagenet_datamodule.py), [KittiDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/kitti_datamodule.py), and [STL10DataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/stl10_datamodule.py) take batch size in constructor, which is used by the `{train,val,test}_dataloader()` methods.

[MNISTDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/mnist_datamodule.py) takes batch size in constructor, but it's not used. `{train,val,test}_dataloader()` methods always use the default value 32.

[BinaryMNISTDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/binary_mnist_datamodule.py), [FashionMNISTDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/fashion_mnist_datamodule.py), [SklearnDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/sklearn_datamodule.py), [SSLImagenetDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/ssl_imagenet_datamodule.py),  and [VOCDetectionDataModule](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/datamodules/vocdetection_datamodule.py) don't take batch size in constructor. These have `{train,val,test}_dataloader()` methods that take a batch size argument, but a trainer always calls them without arguments.

### To Reproduce

To illustrate the problem, the `--batch_size` argument has no effect in the the [FasterRCNN](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/0.2.5/pl_bolts/models/detection/faster_rcnn.py#L126) model.

1. Add `print(batch_size)` to `VOCDetectionDataModule.train_dataloader()`.
2. Run `python faster_rcnn.py --batch_size 10`.
3. See that 1 is printed instead of 10.

### Expected behavior

The batch size argument should be passed in the dataloader calls. This could be fixed by calling

    trainer.fit(model, datamodule.train_dataloader(batch_size), datamodule.val_dataloader(batch_size))

instead of

    trainer.fit(model, datamodule)

I guess it would be better to fix the data modules so that they take batch size in the constructor, though.

### Environment

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8.5

### Additional context

The [DataModule documentation](https://pytorch-lightning.readthedocs.io/en/latest/datamodules.html) could be clearer regarding to how to set the batch size. The first MNISTDataModule example takes the batch size in constructor and saves it in the `batch_size` attribute, which is used by `{train,val,test}_dataloader()`. In the second example, the `{train,val,test}_dataloader()` methods take the batch size as an argument. However, if `Trainer.fit()` is called with a data module, the only way to set the batch size is in the data module constructor.

**Comment by akihironitta** [comment]
@senarvi Thank you for reporting the issue! Actually, @hecoding has pointed it out in #334 and added `batch_size` argument to all datamodules in #344, and the fixes should be merged into the main branch very soon.

> the --batch_size argument has no effect in the the FasterRCNN model.

You're right. We are trying to decouple datamodules from models in #207, and it seems we haven't removed those data-related arguments (e.g. `--batch_size`) from `FasterRCNN` as you pointed out.

> In the second example, the {train,val,test}_dataloader() methods take the batch size as an argument.

Which example are you referring to?

**Comment by senarvi** [comment]
> @senarvi Thank you for reporting the issue! Actually, @hecoding has pointed it out in #334 and added `batch_size` argument to all datamodules in #344, and the fixes should be merged into the main branch very soon.

Great, then I'll close this issue!

> > In the second example, the {train,val,test}_dataloader() methods take the batch size as an argument.
> 
> Which example are you referring to?

Never mind, actually the second example ("Here’s a more realistic, complex DataModule") always uses batch size 32.
