### ISSUE TITLE
Refactor each RL model to not use hparams

### ISSUE THREAD

**Issue by williamFalcon** [PyTorchLightning/pytorch-lightning-bolts#42]
@djbyrne 

Goal is to allow each model to init like:

```python
from pl_bolts.models.rl import DQN

model = DQN()
```

But some models might have required params (but most should have good defaults).

https://files.slack.com/files-pri/TR9DVT48M-F0164T0P03B/image.png

**Comment by djbyrne** [comment]
This should be completed here https://github.com/PyTorchLightning/pytorch-lightning-bolts/pull/56
