### ISSUE TITLE
Cannot import SwAV

### ISSUE THREAD

**Issue by userkkw** [PyTorchLightning/pytorch-lightning-bolts#420]
## 🐛 Bug

`from pl_bolts.models.self_supervised import SwAV` is not working for me.  BYOL and SimCLR all had no problem to import.

### To Reproduce

I installed the package: 
`%pip install -q pytorch-lightning`
`%pip install -q pytorch-lightning-bolts`
then import the package
`import torch`
`import pytorch_lightning as pl`
`from pl_bolts.models.self_supervised import SwAV`

then I got error:
`ImportError: cannot import name 'SwAV'`

### Environment

Google Colab - free tier
AWS Sagemaker - kernel: pytorch-latest-p36 with 8 gpus..

**Comment by akihironitta** [comment]
@userkkw Thank you for reporting the issue. Would you mind upgrading Bolts and retrying?
`pip install git+https://github.com/PytorchLightning/pytorch-lightning-bolts.git@master --upgrade`

**Comment by userkkw** [comment]
@akihironitta it works now thanks :)
