### ISSUE TITLE
(SimClr) ValueError: Input dimension should be at least 3

### ISSUE THREAD

**Issue by RezwanCode** [PyTorchLightning/pytorch-lightning-bolts#424]
ValueError                                Traceback (most recent call last)
<ipython-input-28-5cbe435bea01> in <module>()
     24 model = SimCLR(batch_size=batch_size, num_samples=train_samples)
     25 trainer = pl.Trainer(callbacks=callbacks, progress_bar_refresh_rate=2, gpus=1)
---> 26 trainer.fit(model, dm)

18 frames
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/utils.py in _list_with_default(out_size, defaults)
     32         return out_size
     33     if len(defaults) <= len(out_size):
---> 34         raise ValueError('Input dimension should be at least {}'.format(len(out_size) + 1))
     35     return [v if v is not None else d for v, d in zip(out_size, defaults[-len(out_size):])]

ValueError: Input dimension should be at least 3

**Comment by ananyahjha93** [comment]
same as #416
