### ISSUE TITLE
Training simclr on multi-gpu

### ISSUE THREAD

**Issue by bhat-prashant** [PyTorchLightning/pytorch-lightning-bolts#431]
I see a quite a bit of performance drop in pytorch-lightning implementation vs original simclr implementation for CIFAR-10. 

I have a hypothesis why this could be the case. As I see it, pt-lightning model is trained on 8 GPUs for 800 epochs. That means, in my view, pt-lightning simclr model had only 800 / 8 = 100 updates (considering all data is fed once). If you consider this way, you model is effectively trained only for 100 epochs. 

Please correct me if I am wrong. If otherwise, I would like to know what adjustments did you use when you trained on multi-GPU like DistributedDataparallel or DataParallel etc. 

Thanks
Prashant

**Comment by ananyahjha93** [comment]
Docs needs an update, those performance do not reflect the latest training results, I am working on a docs overhaul. Also, training for 800 epochs on 8 GPUs does not imply we trained for a 100 epochs. All data is split into 8 parts and the model gets to see all examples every epoch.
