### ISSUE TITLE
ci: Enable required isort/mypy check

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#451]
## 🚀 Feature
In order to prevent ci from failing on the master branch like 13863ccf1f96cb912406c029c50f4253f4599aee, shall we make `isort` (`mypy` as well maybe?) check required to pass before merging?

@Borda It seems only admin can enable required checks, so mind considering? [GitHub Docs - Enabling required status checks](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks)

**Comment by Borda** [comment]
Done :]

**Comment by akihironitta** [comment]
That was quick! Thank you :]

**Comment by Borda** [comment]
> That was quick! Thank you :]

I was thinking about it too, and I already did in other repos :]
