### ISSUE TITLE
`global` assignment in warnings.py

### ISSUE THREAD

**Issue by hassiahk** [PyTorchLightning/pytorch-lightning-bolts#461]
I have observed that in `pl_bolts.utils.warnings`, `global` assignment is being used for `MISSING_PACKAGE_WARNINGS` which is causing `CodeFactor` to fail in CI tests. In my opinion, `global` assignment is not needed as `MISSING_PACKAGE_WARNINGS` is already initialized outside the function itself.

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/02684ef4054e38a3b2e4a641821386afeb0f36d6/pl_bolts/utils/warnings.py#L20

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/02684ef4054e38a3b2e4a641821386afeb0f36d6/pl_bolts/utils/warnings.py#L4-L7

Happy to send a PR, if it is okay to remove the `global` assignment. :)

**Comment by akihironitta** [comment]
@hassiahk Thank you for your suggestion! Sounds nice! Could you submit a PR fixing this?

**Comment by hassiahk** [comment]
> @hassiahk Thank you for your suggestion! Sounds nice! Could you submit a PR fixing this?

@akihironitta, sure.
