### ISSUE TITLE
tests: failing due to `argparse.ArgumentError: argument --fast_dev_run: expected one argument`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#471]
## 🐛 Bug
The current tests on the master branch are failing due to:
```
argparse.ArgumentError: argument --fast_dev_run: expected one argument
```

<details><summary>Failing runs</summary><p>

(due to the above error on https://github.com/PyTorchLightning/pytorch-lightning-bolts/commit/a72766c461a498ab67b7c2efe7e0d49224290837 for example)
- https://github.com/PyTorchLightning/pytorch-lightning-bolts/runs/1586140031
- https://github.com/PyTorchLightning/pytorch-lightning-bolts/runs/1586140045

</p></details>

<details><summary>Failing tests</summary><p>

```
tests/models/test_scripts.py::test_cli_run_basic_ae[--dataset cifar10 --data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --max_epochs 1 --batch_size 2 --fast_dev_run]
tests/models/test_scripts.py::test_cli_run_basic_vae[--dataset cifar10 --data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --max_epochs 1 --batch_size 2 --fast_dev_run]
tests/models/rl/test_scripts.py::test_cli_run_rl_dqn[--env PongNoFrameskip-v4 --max_steps 10 --fast_dev_run --warm_start_size 10 --n_steps 2 --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_double_dqn[--env PongNoFrameskip-v4 --max_steps 10 --fast_dev_run --warm_start_size 10 --n_steps 2 --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_dueling_dqn[--env PongNoFrameskip-v4 --max_steps 10 --fast_dev_run --warm_start_size 10 --n_steps 2 --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_noisy_dqn[--env PongNoFrameskip-v4 --max_steps 10 --fast_dev_run --warm_start_size 10 --n_steps 2 --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_per_dqn[--env PongNoFrameskip-v4 --max_steps 10 --fast_dev_run --warm_start_size 10 --n_steps 2 --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_reinforce[--env CartPole-v0 --max_steps 10 --fast_dev_run --batch_size 10]
tests/models/rl/test_scripts.py::test_cli_run_rl_vanilla_policy_gradient[--env CartPole-v0 --max_steps 10 --fast_dev_run --batch_size 10]
tests/models/self_supervised/test_scripts.py::test_cli_run_self_supervised_amdim[--data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --max_epochs 1 --max_steps 3 --fast_dev_run --batch_size 2]
tests/models/self_supervised/test_scripts.py::test_cli_run_self_supervised_moco[--data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --max_epochs 1 --max_steps 3 --fast_dev_run --batch_size 2]
tests/models/self_supervised/test_scripts.py::test_cli_run_self_supervised_byol[--data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --max_epochs 1 --max_steps 3 --fast_dev_run --batch_size 2 --online_ft]
```

</p></details>

### To Reproduce
It looks tests on {macOS, Ubuntu} x {3.6} are failing...
further investigating...

**Comment by akihironitta** [comment]
I was guessing that all tests with `--fast_dev_run` are failing, but that's not true as the following test which has `--fast_dev_run` passes:
```
tests/models/self_supervised/test_scripts.py::test_cli_run_self_supervised_simclr[--data_dir /home/runner/work/pytorch-lightning-bolts/pytorch-lightning-bolts/datasets --gpus 0 --fp32 --max_epochs 1 --max_steps 3 --fast_dev_run --batch_size 2 --online_ft] PASSED [ 83%]
```

**Comment by Borda** [comment]
I feel that the problem is that this fast dev is not the one taken from Trainer but coded/added extra...

**Comment by akihironitta** [comment]
You're right. The models passing the tests have their own `--fast_dev_run`. I'm not sure yet why the tests for the rest models fail only on Python 3.6 though.

Do you think it's reasonable to add `--fast_dev_run` to the other models for now? (although I think  `--fast_dev_run` should be included not in models but in trainer...)

**Comment by akihironitta** [comment]
@ananyahjha93 I looked through the changelog (3.6->3.7) of argparse and the docs and tried to locate how `this fast dev is not the one taken from Trainer but coded/added extra...` as @Borda mentioned, but I couldn't find a way to solve this problem.

An easy workaround to fix this error would be to add `--fast_dev_run` args to faiilng models... https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/471#issuecomment-750794733

**Comment by MaveriQ** [comment]
I resolved this by passing `--fast_dev_run 1` as command line argument
