### ISSUE TITLE
[coverage] Use `no cover` instead of `no-cover`

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#476]
## 🚀 Refactoring
As far as I know from
- the docs: https://coverage.readthedocs.io/en/latest/excluding.html
- the number of search results on GitHub
  - `pragma: no cover` https://github.com/search?l=Python&q=pragma%3A+no+cover&type=code
  - `pragma: no-cover` https://github.com/search?l=Python&q=pragma%3A+no-cover&type=code

, we should use `pragma: no cover` instead of `pragma: no-cover`. I guess there's no difference between them, but most of the projects employ `pragma: no cover` as in the docs. (This should not be a high priority, but for consistency, we can start to use `no cover`.)

**Comment by Borda** [comment]
@akihironitta are these two PRs all that is needed to fix it?

**Comment by akihironitta** [comment]
It looks like I missed some, so let me include all of the missed ones in #524. Once #524 is resolved, we can close this issue.
