### ISSUE TITLE
ci: Introduce code formatter

### ISSUE THREAD

**Issue by akihironitta** [PyTorchLightning/pytorch-lightning-bolts#482]
## 🚀 Feature
We've spent quite some time on fixing code formatting in code reviews by our own hands, but this should be done automatically by a Python code formatter.

### List of formatters
- `black` by Python Software Foundation (https://github.com/psf/black)
  - [This blog post by DeepSource](https://deepsource.io/blog/python-code-formatters/) says `black` is the most popular one.
- `yapf` by Google (https://github.com/google/yapf)
- (`autopep8`, ...)

### Additional context
I have used `black` with `isort` (for import formatting) and `flake8` (for pep8 check) in [Optuna](https://github.com/optuna/optuna), and it worked really well, so +1 for `black`.

In PL, `black` was added in https://github.com/PyTorchLightning/pytorch-lightning/pull/1610, but it hasn't been really used... We can start to employ the code formatter here, and if there seems no problem with it, we can enable it in PL later, too.

cc: @Borda @PyTorchLightning/bolts-contributors

**Comment by oke-aditya** [comment]
I have used black earlier and we can add a simple CI check for it as well.
At places there are few collisions with `black` and `flake8`. I'm not sure if both can be together.
Black checks for linting errors too I think.

Also we can add to [`pre-commit-config.yaml`](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/master/.pre-commit-config.yaml)file present in bolts.

**Comment by briankosw** [comment]
> At places there are few collisions with black and flake8. I'm not sure if both can be together.

They can definitely work together, and [black](https://black.readthedocs.io/en/stable/compatible_configs.html) themselves published suggestions on how to make `black` work together with other tools such as `flake8` and `isort`.

I think using `black` will significantly increase pl_bolts' formatting (and therefore code quality), so I'd be happy to help in anyway with adding this to the current array of CI tools.

**Comment by oke-aditya** [comment]
I read the above black page, I think it will work fine as they have mentioned.
They have also mentioned how to use with precommite [here](https://black.readthedocs.io/en/stable/version_control_integration.html)
and Github CI action [here](https://black.readthedocs.io/en/stable/github_actions.html)

Plus add it to readme badge :smile: like [this](https://black.readthedocs.io/en/stable/show_your_style.html)

**Comment by akihironitta** [comment]
@oke-aditya @briankosw Thank you both for sharing the useful information!
So, as I read your comments, I believe we should do the followings:
1. add `black` to pre-commit hooks
   - https://black.readthedocs.io/en/stable/version_control_integration.html
2. add `black` to GitHub Actions
   - https://black.readthedocs.io/en/stable/github_actions.html
3. update `flake8` and `isort` configs to avoid conflicts with `black`
   - https://black.readthedocs.io/en/stable/compatible_configs.html
4. add the badge to readme
   - https://black.readthedocs.io/en/stable/show_your_style.html

Let's get to work on this once we have positive comments from other core members :]

**Comment by akihironitta** [comment]
@Borda Shall we introduce `black` so that we can easily check formatting including `trailing-whitespaces` in the pre-commit, and we don't need another PR like https://github.com/PyTorchLightning/pytorch-lightning/pull/5387 in the future?

**Comment by Borda** [comment]
> we can easily check formatting including `trailing-whitespaces`

I think that we can do this check with `flake8` right?
but yes, lest try black here :]

**Comment by akihironitta** [comment]
@Borda I've just noticed your updated comment (though I already created a draft PR #507 to add black).

I agree that `COALESCE_BRACKETS` of `yapf` looks neat! Using `black` would be easier since it is widely used and has fewer parameters (and I've used it before), but we could use `yapf` if you'd like :]

@oke-aditya @briankosw Please leave your comments if you've got any.

**Comment by Borda** [comment]
Personally I would prefer flexibility over mainstream... I would not be affraid of using yapf since it Facebook in house tool...

**Comment by oke-aditya** [comment]
I have used black. I do not like it much. it makes code too lengthy and is very strict checker, also collides with isort and flake8.

I'm not sure how to configure yapf, how to add CI, pre commit though. I agree with @Borda's suggestion. I would like a flexible formatted (like flake8). Also facebook style would be preferred.

**Comment by Borda** [comment]
for the record, this is the proposed config
```
[yapf]
based_on_style = pep8
spaces_before_comment = 2
split_before_logical_operator = true
COLUMN_LIMIT = 120
COALESCE_BRACKETS = true
DEDENT_CLOSING_BRACKETS = true
ALLOW_SPLIT_BEFORE_DICT_VALUE = false
BLANK_LINE_BEFORE_NESTED_CLASS_OR_DEF = true
NO_SPACES_AROUND_SELECTED_BINARY_OPERATORS = false
```
