### ISSUE TITLE
Pillow version

### ISSUE THREAD

**Issue by sho-87** [PyTorchLightning/pytorch-lightning-bolts#485]
## 🐛 Bug

Pillow version 8.0.1 doesnt seem to satisfy the requirements of the package, even though there is no specific version numbered required. With Pillow 8.0.1 installed, attempting to `pip install pytorch-lightning-bolts["extra"]` will try to uninstall (downgrade) the Pillow version. Maybe placing a minimum pillow version requirement would fix this?

```
> pip install pytorch-lightning-bolts["extra"]

Requirement already satisfied: Pillow in c:\users\simon\anaconda3\envs\pytorch\lib\site-packages (from pytorch-lightning-bolts[extra]) (8.0.1)
Collecting Pillow
  Downloading Pillow-7.2.0-cp38-cp38-win_amd64.whl (2.1 MB)

Installing collected packages: pyglet, Pillow, pytorch-lightning-bolts, opencv-python, gym
  Attempting uninstall: Pillow
    Found existing installation: Pillow 8.0.1
    Uninstalling Pillow-8.0.1:
      Successfully uninstalled Pillow-8.0.1
```

### To Reproduce

1. Install pytorch/lightning and Pillow 8.0.1 in a conda environment
2. `pip install pytorch-lightning-bolts["extra"]`

### Environment

 - PyTorch Version (e.g., 1.0): 1.1.2
 - OS (e.g., Linux): Windows
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8
 - CUDA/cuDNN version: 10.1

**Comment by akihironitta** [comment]
@sho-87 Thank you for reporting the issue. Let me look into it.

**Comment by akihironitta** [comment]
As I checked locally, I was able to reproduce the behaviour.

### Environment
- OS (e.g., Linux): Linux
- How you installed PyTorch (`conda`, `pip`, source): pip
- Python version: 3.8.5
- CUDA/cuDNN version: None
- `pip list`
  ```
  pytorch-lightning       1.1.2
  pytorch-lightning-bolts 0.2.5
  torch                   1.7.1
  ```

---
@sho-87  Currently, Bolts doesn't specify any min version for `Pillow` as you're aware. If you ran `pip show Pillow`, you'll find out that `gym` and `torchvision` depend on `Pillow`, and it seems only `gym` tries to downgrade `Pillow==8.0.1` to `Pillow==7.2.0`.

As `gym` needs `Pillow==7.2.0` (for some reason), I'd keep Bolts' requirement as is. Do you still think we should set the min requirement as `Pillow==8.0` or something in Bolts?

**Comment by sho-87** [comment]
ah I see. didnt realize the gym requirement was `Pillow<=7.2.0`. Probably best to keep Bolts as is then. Thanks for checking
