### ISSUE TITLE
Add Pix2Pix

### ISSUE THREAD

**Issue by aniketmaurya** [PyTorchLightning/pytorch-lightning-bolts#512]
## 🚀 Feature
Pix2Pix is a really good example of image-to-image translation network and should be included in Lightning.

### Motivation

Currently Lightning doesn't have Pix2Pix model implemented. As it is a good starting example for anyone learning GANs, it should be easily accessible for training and experimenting with custom dataset.

### Pitch

I would like to take the responsibility of implementing Pix2Pix in Lightning.

### Alternatives

Many good examples are already available in PyTorch. For example- https://github.com/mrzhu-cool/pix2pix-pytorch

**Comment by akihironitta** [comment]
@aniketmaurya Thank you for your suggestion! It'd be great to have this model in Bolts!
