### ISSUE TITLE
cannot import name SwAV

### ISSUE THREAD

**Issue by rahul-art** [PyTorchLightning/pytorch-lightning-bolts#513]
### To Reproduce

1. while importing SwAV
![swav_error](https://user-images.githubusercontent.com/56379013/104735659-db741d00-5767-11eb-8ca2-cf0e8561968e.png)

**Comment by akihironitta** [comment]
@rahul-art Thank you for reporting the issue! Would you mind updating it to the latest version and retry?
```
pip install git+https://github.com/PytorchLightning/pytorch-lightning-bolts.git@master --upgrade
```

**Comment by Borda** [comment]
isnt SaW depending on torchvision?

**Comment by akihironitta** [comment]
Yes, but if any optional packages needed for the class are missing, it'll raise an exception when instantiating it, so there should be no problem when importing the class.
