### ISSUE TITLE
DQN run_n_episodes ignores environment parameter

### ISSUE THREAD

**Issue by WeberSamuel** [PyTorchLightning/pytorch-lightning-bolts#516]
## 🐛 Bug

The method ``run_n_episodes`` takes an environment as parameter, that should be used to run a specific number of episodes. But instead it uses the objects environment (`self.env` and not the parameter `env`) to run the simulation steps.

This bug also causes warnings when testing the DQN model, as the passed environment is resetted, but the environment to run the simulation steps on is not reseted and thus may be in an invalid state (e.g. already finished).

### Additional context
The bug is caused by [line 175 in dqn_model.py](https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/413b9df0d615fb6dbfe0bdc00f905ab7c4aed07d/pl_bolts/models/rl/dqn_model.py#L175).

**Comment by sid-sundrani** [comment]
Yes, I agree with that. Even in `test_step`, `self.test_env` is passed to `run_n_episodes` but `self.env` is used instead in `run_n_episodes`

**Comment by Borda** [comment]
it shall be just about using args, right, @sid-sundrani are you interested in sending fix?
