### ISSUE TITLE
Slightly incorrect documentation for VAE

### ISSUE THREAD

**Issue by jeremyadamsfisher** [PyTorchLightning/pytorch-lightning-bolts#543]
The example for a VAE indicates that `from_pretrained` is a static method 

https://github.com/PyTorchLightning/pytorch-lightning-bolts/blob/4e1c1502b70e4be59a9ac80878ec5ad5a212f87e/pl_bolts/models/autoencoders/basic_vae/basic_vae_module.py#L30

Indeed, running this line causes as error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-64-4c7d0e8ca436> in <module>
----> 1 vae = VAE.from_pretrained('cifar10-resnet18')

TypeError: from_pretrained() missing 1 required positional argument: 'checkpoint_name'
```

This is because the method is actually implemented nonstatically:
```python
def from_pretrained(self, checkpoint_name):
    if checkpoint_name not in VAE.pretrained_urls:
        raise KeyError(str(checkpoint_name) + ' not present in pretrained weights.')

    return self.load_from_checkpoint(VAE.pretrained_urls[checkpoint_name], strict=False)
```
Seems to me either:
- the documentation should to reflect this (`vae = VAE(32).from_pretrained(...)`)
- the method should be rewritten
```python
@classmethod
def from_pretrained(cls, checkpoint_name):
    # snip
    return self.load_from_checkpoint(cls(32).pretrained_urls[checkpoint_name], strict=False)
```

Here is a minimal failing example on colab: [https://colab.research.google.com/drive/1quvrQUyCIMC7Cq9QCjaJfip5hsi9jwSJ?usp=sharing](https://colab.research.google.com/drive/1quvrQUyCIMC7Cq9QCjaJfip5hsi9jwSJ?usp=sharing)

Happy to write a PR, if desired

**Comment by akihironitta** [comment]
@jeremyadamsfisher Hi, thank you for reporting the issue! Following the suggestion by @ananyahjha93 in https://github.com/PyTorchLightning/pytorch-lightning-bolts/issues/200#issuecomment-691534816, let's just fix the docs for now.
> 2. `from_pretrained()` needs to be an instance method and not a static method. In most cases, you will initialize the lightning module with specific params according the the weights being loaded.

**Comment by akihironitta** [comment]
@jeremyadamsfisher Would you be interested in submitting a PR?

**Comment by jeremyadamsfisher** [comment]
You got it
