### ISSUE TITLE
Bolts Vision Models not working

### ISSUE THREAD

**Issue by kunal-savvy** [PyTorchLightning/pytorch-lightning-bolts#559]
## 🐛 Bug- Image GPT Bolts models not getting imported. Same issue for segment models 
![Screenshot_2021-02-15 Untitled - Jupyter Notebook(1)](https://user-images.githubusercontent.com/21246183/107978111-3fb61680-6f8a-11eb-8fd1-ad94f143cd4c.png)
![Screenshot_2021-02-15 Untitled - Jupyter Notebook](https://user-images.githubusercontent.com/21246183/107978115-40e74380-6f8a-11eb-919d-7aa320967b64.png)

### To Reproduce

1. Go to '...'pip install
2. Run '....' import 

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by akihironitta** [comment]
@kunal-savvy Hi, thank you for reporting the issue!

For `ImageGPT`, a quick workaround would be:
```python
from pl_bolts.models.vision.image_gpt.igpt_module import ImageGPT
```
, but this problem should be resolved in no time.

For `KittiDataModule`, we previously had problems in importing some names, but I think it should be resolved on the current master, so could you please upgrade Bolts by running:
```console
$ pip install git+https://github.com/PytorchLightning/pytorch-lightning-bolts.git@master --upgrade
```

Please let us know if it still doesn't work. Sorry for your inconvenience.

**Comment by kunal-savvy** [comment]
Thanks, it helps but documentation on "vision" models is lacking. Its not clear how to get output from them (like imagegpt2). We have to revert to full github code for it. While import worked, there is a new issue now; which I will add to different thread.

**Comment by kunal-savvy** [comment]
Kitty error - "
ImportError: cannot import name 'KittiDataModule' from 'pl_bolts.datamodules' (/opt/anaconda3/lib/python3.7/site-packages/pl_bolts/datamodules/__init__.py)"

**Comment by akihironitta** [comment]
> documentation on "vision" models is lacking. Its not clear how to get output from them (like imagegpt2). We have to revert to full github code for it. While image GPT2 import worked, there is a new issue now;

@kunal-savvy I agree, the docs could be better for sure. I'll create an issue for that.

> The kitty module import still throws same error even after upgrade.

Could you run the command and share the output like below?
```console
$ wget https://raw.githubusercontent.com/PyTorchLightning/pytorch-lightning/master/tests/collect_env_details.py
$ python collect_env_details.py
* CUDA:
	- GPU:
	- available:         False
	- version:           10.2
* Packages:
	- numpy:             1.20.1
	- pyTorch_debug:     False
	- pyTorch_version:   1.7.1
	- pytorch-lightning: 1.1.8
	- tqdm:              4.57.0
* System:
	- OS:                Linux
	- architecture:
		- 64bit
		- ELF
	- processor:         
	- python:            3.8.5
	- version:           #1 SMP Debian 4.19.171-2 (2021-01-30)
```

**Comment by maulberto3** [comment]
I tried to run on kaggle.com the CIFAR tutorial, but still have not yet successfully installed the pl bolts package: ImportError: cannot import name 'emnist_normalization' from 'pl_bolts.transforms.dataset_normalizations'
