### ISSUE TITLE
LatentDImInterpolator change num_images calculation

### ISSUE THREAD

**Issue by FlorianMF** [PyTorchLightning/pytorch-lightning-bolts#571]
### To Reproduce
pass LatentDImInterpolator as callback to the lightning trainer.

use the default args: range_start=-5, range_end=5, steps=11

Train a GAN on some data (eg. a vanilla GAN on MNIST)

### Expected behavior
The interpolator creates 11 examples along each dimension (11x11)
Hence, num_images should be 121 and num_rows 11

The calculation though is only based on range_start and range_end: 
num_images = (self.range_end - self.range_start)**2
num_rows = int(math.sqrt(num_images))

This results in num_images=10 and num_rows=10

In the Logger (Tensorboard) you obtain an image with 10 columns x 13 rows. In the last row there is a single image.

I suppose that the intention was to generate a rectangular image.

I don't think that simply setting steps=10 is a good solution if the interpolated values should still be integers as in the example (-5, -4, -3, ..., 3, 4, 5).
Probably it would be enough to set num_rows to steps.

### Environment

 - PyTorch Version (e.g., 1.0):
 - PL Bolts version: 0.3.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): -
 - Python version: 3.9

**Comment by tchaton** [comment]
Dear @FlorianMF,

Great catch ! Would you like to submit a PR to fix `LatentDImInterpolator` ?

Best,
T.C

**Comment by FlorianMF** [comment]
Would you be OK changing the code as follows: 
num_rows = int(math.sqrt(steps)) 
and drop num_images = (self.range_end - self.range_start)**2 ?
